apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: skaffold-example
      context: .

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: skaffold-example
          context: .
          sync:
            manual:
              - src: "main.go"
                dest: "."
