# Default values for exampleapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: skaffold-example

image:
  repository: skaffold-example
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

labels:
  app: skaffold-example

selectorLabels:
  app: skaffold-example

service:
  type: ClusterIP
  port: 3000
